// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageJob.proto

package TestMain;

public final class MessageImplementation {
  private MessageImplementation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageJobOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestMain.MessageJob)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string origin = 1;</code>
     */
    boolean hasOrigin();
    /**
     * <code>required string origin = 1;</code>
     */
    java.lang.String getOrigin();
    /**
     * <code>required string origin = 1;</code>
     */
    com.google.protobuf.ByteString
        getOriginBytes();

    /**
     * <code>required string destiny = 2;</code>
     */
    boolean hasDestiny();
    /**
     * <code>required string destiny = 2;</code>
     */
    java.lang.String getDestiny();
    /**
     * <code>required string destiny = 2;</code>
     */
    com.google.protobuf.ByteString
        getDestinyBytes();

    /**
     * <code>required .TestMain.MessageJob.Priority prior = 3;</code>
     */
    boolean hasPrior();
    /**
     * <code>required .TestMain.MessageJob.Priority prior = 3;</code>
     */
    TestMain.MessageImplementation.MessageJob.Priority getPrior();
  }
  /**
   * Protobuf type {@code TestMain.MessageJob}
   */
  public  static final class MessageJob extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TestMain.MessageJob)
      MessageJobOrBuilder {
    // Use MessageJob.newBuilder() to construct.
    private MessageJob(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageJob() {
      origin_ = "";
      destiny_ = "";
      prior_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageJob(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              origin_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              destiny_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              TestMain.MessageImplementation.MessageJob.Priority value = TestMain.MessageImplementation.MessageJob.Priority.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                prior_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TestMain.MessageImplementation.internal_static_TestMain_MessageJob_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TestMain.MessageImplementation.internal_static_TestMain_MessageJob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TestMain.MessageImplementation.MessageJob.class, TestMain.MessageImplementation.MessageJob.Builder.class);
    }

    /**
     * Protobuf enum {@code TestMain.MessageJob.Priority}
     */
    public enum Priority
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HIGH = 0;</code>
       */
      HIGH(0),
      /**
       * <code>LOW = 1;</code>
       */
      LOW(1),
      ;

      /**
       * <code>HIGH = 0;</code>
       */
      public static final int HIGH_VALUE = 0;
      /**
       * <code>LOW = 1;</code>
       */
      public static final int LOW_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Priority valueOf(int value) {
        return forNumber(value);
      }

      public static Priority forNumber(int value) {
        switch (value) {
          case 0: return HIGH;
          case 1: return LOW;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Priority>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Priority> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Priority>() {
              public Priority findValueByNumber(int number) {
                return Priority.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return TestMain.MessageImplementation.MessageJob.getDescriptor().getEnumTypes().get(0);
      }

      private static final Priority[] VALUES = values();

      public static Priority valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Priority(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:TestMain.MessageJob.Priority)
    }

    private int bitField0_;
    public static final int ORIGIN_FIELD_NUMBER = 1;
    private volatile java.lang.Object origin_;
    /**
     * <code>required string origin = 1;</code>
     */
    public boolean hasOrigin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string origin = 1;</code>
     */
    public java.lang.String getOrigin() {
      java.lang.Object ref = origin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          origin_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string origin = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOriginBytes() {
      java.lang.Object ref = origin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        origin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTINY_FIELD_NUMBER = 2;
    private volatile java.lang.Object destiny_;
    /**
     * <code>required string destiny = 2;</code>
     */
    public boolean hasDestiny() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string destiny = 2;</code>
     */
    public java.lang.String getDestiny() {
      java.lang.Object ref = destiny_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destiny_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string destiny = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDestinyBytes() {
      java.lang.Object ref = destiny_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destiny_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIOR_FIELD_NUMBER = 3;
    private int prior_;
    /**
     * <code>required .TestMain.MessageJob.Priority prior = 3;</code>
     */
    public boolean hasPrior() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .TestMain.MessageJob.Priority prior = 3;</code>
     */
    public TestMain.MessageImplementation.MessageJob.Priority getPrior() {
      TestMain.MessageImplementation.MessageJob.Priority result = TestMain.MessageImplementation.MessageJob.Priority.valueOf(prior_);
      return result == null ? TestMain.MessageImplementation.MessageJob.Priority.HIGH : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOrigin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDestiny()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrior()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, origin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, destiny_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, prior_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, origin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, destiny_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, prior_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TestMain.MessageImplementation.MessageJob)) {
        return super.equals(obj);
      }
      TestMain.MessageImplementation.MessageJob other = (TestMain.MessageImplementation.MessageJob) obj;

      boolean result = true;
      result = result && (hasOrigin() == other.hasOrigin());
      if (hasOrigin()) {
        result = result && getOrigin()
            .equals(other.getOrigin());
      }
      result = result && (hasDestiny() == other.hasDestiny());
      if (hasDestiny()) {
        result = result && getDestiny()
            .equals(other.getDestiny());
      }
      result = result && (hasPrior() == other.hasPrior());
      if (hasPrior()) {
        result = result && prior_ == other.prior_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOrigin()) {
        hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
        hash = (53 * hash) + getOrigin().hashCode();
      }
      if (hasDestiny()) {
        hash = (37 * hash) + DESTINY_FIELD_NUMBER;
        hash = (53 * hash) + getDestiny().hashCode();
      }
      if (hasPrior()) {
        hash = (37 * hash) + PRIOR_FIELD_NUMBER;
        hash = (53 * hash) + prior_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TestMain.MessageImplementation.MessageJob parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestMain.MessageImplementation.MessageJob parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestMain.MessageImplementation.MessageJob parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestMain.MessageImplementation.MessageJob parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestMain.MessageImplementation.MessageJob parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TestMain.MessageImplementation.MessageJob parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TestMain.MessageImplementation.MessageJob parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TestMain.MessageImplementation.MessageJob parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TestMain.MessageImplementation.MessageJob parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TestMain.MessageImplementation.MessageJob parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TestMain.MessageImplementation.MessageJob prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestMain.MessageJob}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestMain.MessageJob)
        TestMain.MessageImplementation.MessageJobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TestMain.MessageImplementation.internal_static_TestMain_MessageJob_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TestMain.MessageImplementation.internal_static_TestMain_MessageJob_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TestMain.MessageImplementation.MessageJob.class, TestMain.MessageImplementation.MessageJob.Builder.class);
      }

      // Construct using TestMain.MessageImplementation.MessageJob.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        origin_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        destiny_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        prior_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TestMain.MessageImplementation.internal_static_TestMain_MessageJob_descriptor;
      }

      public TestMain.MessageImplementation.MessageJob getDefaultInstanceForType() {
        return TestMain.MessageImplementation.MessageJob.getDefaultInstance();
      }

      public TestMain.MessageImplementation.MessageJob build() {
        TestMain.MessageImplementation.MessageJob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TestMain.MessageImplementation.MessageJob buildPartial() {
        TestMain.MessageImplementation.MessageJob result = new TestMain.MessageImplementation.MessageJob(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.origin_ = origin_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.destiny_ = destiny_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.prior_ = prior_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TestMain.MessageImplementation.MessageJob) {
          return mergeFrom((TestMain.MessageImplementation.MessageJob)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TestMain.MessageImplementation.MessageJob other) {
        if (other == TestMain.MessageImplementation.MessageJob.getDefaultInstance()) return this;
        if (other.hasOrigin()) {
          bitField0_ |= 0x00000001;
          origin_ = other.origin_;
          onChanged();
        }
        if (other.hasDestiny()) {
          bitField0_ |= 0x00000002;
          destiny_ = other.destiny_;
          onChanged();
        }
        if (other.hasPrior()) {
          setPrior(other.getPrior());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOrigin()) {
          return false;
        }
        if (!hasDestiny()) {
          return false;
        }
        if (!hasPrior()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TestMain.MessageImplementation.MessageJob parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TestMain.MessageImplementation.MessageJob) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object origin_ = "";
      /**
       * <code>required string origin = 1;</code>
       */
      public boolean hasOrigin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string origin = 1;</code>
       */
      public java.lang.String getOrigin() {
        java.lang.Object ref = origin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            origin_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string origin = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOriginBytes() {
        java.lang.Object ref = origin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          origin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string origin = 1;</code>
       */
      public Builder setOrigin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        origin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string origin = 1;</code>
       */
      public Builder clearOrigin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        origin_ = getDefaultInstance().getOrigin();
        onChanged();
        return this;
      }
      /**
       * <code>required string origin = 1;</code>
       */
      public Builder setOriginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        origin_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object destiny_ = "";
      /**
       * <code>required string destiny = 2;</code>
       */
      public boolean hasDestiny() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string destiny = 2;</code>
       */
      public java.lang.String getDestiny() {
        java.lang.Object ref = destiny_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            destiny_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string destiny = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDestinyBytes() {
        java.lang.Object ref = destiny_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destiny_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string destiny = 2;</code>
       */
      public Builder setDestiny(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        destiny_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string destiny = 2;</code>
       */
      public Builder clearDestiny() {
        bitField0_ = (bitField0_ & ~0x00000002);
        destiny_ = getDefaultInstance().getDestiny();
        onChanged();
        return this;
      }
      /**
       * <code>required string destiny = 2;</code>
       */
      public Builder setDestinyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        destiny_ = value;
        onChanged();
        return this;
      }

      private int prior_ = 0;
      /**
       * <code>required .TestMain.MessageJob.Priority prior = 3;</code>
       */
      public boolean hasPrior() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .TestMain.MessageJob.Priority prior = 3;</code>
       */
      public TestMain.MessageImplementation.MessageJob.Priority getPrior() {
        TestMain.MessageImplementation.MessageJob.Priority result = TestMain.MessageImplementation.MessageJob.Priority.valueOf(prior_);
        return result == null ? TestMain.MessageImplementation.MessageJob.Priority.HIGH : result;
      }
      /**
       * <code>required .TestMain.MessageJob.Priority prior = 3;</code>
       */
      public Builder setPrior(TestMain.MessageImplementation.MessageJob.Priority value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        prior_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .TestMain.MessageJob.Priority prior = 3;</code>
       */
      public Builder clearPrior() {
        bitField0_ = (bitField0_ & ~0x00000004);
        prior_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TestMain.MessageJob)
    }

    // @@protoc_insertion_point(class_scope:TestMain.MessageJob)
    private static final TestMain.MessageImplementation.MessageJob DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TestMain.MessageImplementation.MessageJob();
    }

    public static TestMain.MessageImplementation.MessageJob getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MessageJob>
        PARSER = new com.google.protobuf.AbstractParser<MessageJob>() {
      public MessageJob parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MessageJob(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageJob> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageJob> getParserForType() {
      return PARSER;
    }

    public TestMain.MessageImplementation.MessageJob getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestMain_MessageJob_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestMain_MessageJob_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020MessageJob.proto\022\010TestMain\"z\n\nMessageJ" +
      "ob\022\016\n\006origin\030\001 \002(\t\022\017\n\007destiny\030\002 \002(\t\022,\n\005p" +
      "rior\030\003 \002(\0162\035.TestMain.MessageJob.Priorit" +
      "y\"\035\n\010Priority\022\010\n\004HIGH\020\000\022\007\n\003LOW\020\001B!\n\010Test" +
      "MainB\025MessageImplementation"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TestMain_MessageJob_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestMain_MessageJob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestMain_MessageJob_descriptor,
        new java.lang.String[] { "Origin", "Destiny", "Prior", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
