// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageJob.proto

package MessageDef;

public final class MessageImplementation {
  private MessageImplementation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageJobOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProyectoDistribuidos.MessageJob)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string origin = 1;</code>
     */
    boolean hasOrigin();
    /**
     * <code>required string origin = 1;</code>
     */
    java.lang.String getOrigin();
    /**
     * <code>required string origin = 1;</code>
     */
    com.google.protobuf.ByteString
        getOriginBytes();

    /**
     * <code>required string destiny = 2;</code>
     */
    boolean hasDestiny();
    /**
     * <code>required string destiny = 2;</code>
     */
    java.lang.String getDestiny();
    /**
     * <code>required string destiny = 2;</code>
     */
    com.google.protobuf.ByteString
        getDestinyBytes();

    /**
     * <code>required .ProyectoDistribuidos.MessageJob.Priority prior = 3;</code>
     */
    boolean hasPrior();
    /**
     * <code>required .ProyectoDistribuidos.MessageJob.Priority prior = 3;</code>
     */
    MessageDef.MessageImplementation.MessageJob.Priority getPrior();

    /**
     * <code>required .ProyectoDistribuidos.MessageJob.clientInfo info = 4;</code>
     */
    boolean hasInfo();
    /**
     * <code>required .ProyectoDistribuidos.MessageJob.clientInfo info = 4;</code>
     */
    MessageDef.MessageImplementation.MessageJob.clientInfo getInfo();
    /**
     * <code>required .ProyectoDistribuidos.MessageJob.clientInfo info = 4;</code>
     */
    MessageDef.MessageImplementation.MessageJob.clientInfoOrBuilder getInfoOrBuilder();

    /**
     * <code>required .ProyectoDistribuidos.MessageJob.Operation op = 5;</code>
     */
    boolean hasOp();
    /**
     * <code>required .ProyectoDistribuidos.MessageJob.Operation op = 5;</code>
     */
    MessageDef.MessageImplementation.MessageJob.Operation getOp();
  }
  /**
   * Protobuf type {@code ProyectoDistribuidos.MessageJob}
   */
  public  static final class MessageJob extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProyectoDistribuidos.MessageJob)
      MessageJobOrBuilder {
    // Use MessageJob.newBuilder() to construct.
    private MessageJob(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageJob() {
      origin_ = "";
      destiny_ = "";
      prior_ = 0;
      op_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageJob(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              origin_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              destiny_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              MessageDef.MessageImplementation.MessageJob.Priority value = MessageDef.MessageImplementation.MessageJob.Priority.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                prior_ = rawValue;
              }
              break;
            }
            case 34: {
              MessageDef.MessageImplementation.MessageJob.clientInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(MessageDef.MessageImplementation.MessageJob.clientInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              MessageDef.MessageImplementation.MessageJob.Operation value = MessageDef.MessageImplementation.MessageJob.Operation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                op_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageDef.MessageImplementation.internal_static_ProyectoDistribuidos_MessageJob_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageDef.MessageImplementation.internal_static_ProyectoDistribuidos_MessageJob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageDef.MessageImplementation.MessageJob.class, MessageDef.MessageImplementation.MessageJob.Builder.class);
    }

    /**
     * Protobuf enum {@code ProyectoDistribuidos.MessageJob.Operation}
     */
    public enum Operation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CREATE = 0;</code>
       */
      CREATE(0),
      /**
       * <code>CANCEL = 1;</code>
       */
      CANCEL(1),
      /**
       * <code>READ = 2;</code>
       */
      READ(2),
      ;

      /**
       * <code>CREATE = 0;</code>
       */
      public static final int CREATE_VALUE = 0;
      /**
       * <code>CANCEL = 1;</code>
       */
      public static final int CANCEL_VALUE = 1;
      /**
       * <code>READ = 2;</code>
       */
      public static final int READ_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Operation valueOf(int value) {
        return forNumber(value);
      }

      public static Operation forNumber(int value) {
        switch (value) {
          case 0: return CREATE;
          case 1: return CANCEL;
          case 2: return READ;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Operation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
              public Operation findValueByNumber(int number) {
                return Operation.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MessageDef.MessageImplementation.MessageJob.getDescriptor().getEnumTypes().get(0);
      }

      private static final Operation[] VALUES = values();

      public static Operation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Operation(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ProyectoDistribuidos.MessageJob.Operation)
    }

    /**
     * Protobuf enum {@code ProyectoDistribuidos.MessageJob.Priority}
     */
    public enum Priority
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HIGH = 0;</code>
       */
      HIGH(0),
      /**
       * <code>LOW = 1;</code>
       */
      LOW(1),
      ;

      /**
       * <code>HIGH = 0;</code>
       */
      public static final int HIGH_VALUE = 0;
      /**
       * <code>LOW = 1;</code>
       */
      public static final int LOW_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Priority valueOf(int value) {
        return forNumber(value);
      }

      public static Priority forNumber(int value) {
        switch (value) {
          case 0: return HIGH;
          case 1: return LOW;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Priority>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Priority> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Priority>() {
              public Priority findValueByNumber(int number) {
                return Priority.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MessageDef.MessageImplementation.MessageJob.getDescriptor().getEnumTypes().get(1);
      }

      private static final Priority[] VALUES = values();

      public static Priority valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Priority(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ProyectoDistribuidos.MessageJob.Priority)
    }

    public interface clientInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ProyectoDistribuidos.MessageJob.clientInfo)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string IP = 1;</code>
       */
      boolean hasIP();
      /**
       * <code>required string IP = 1;</code>
       */
      java.lang.String getIP();
      /**
       * <code>required string IP = 1;</code>
       */
      com.google.protobuf.ByteString
          getIPBytes();

      /**
       * <code>required int32 Port = 2;</code>
       */
      boolean hasPort();
      /**
       * <code>required int32 Port = 2;</code>
       */
      int getPort();
    }
    /**
     * Protobuf type {@code ProyectoDistribuidos.MessageJob.clientInfo}
     */
    public  static final class clientInfo extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ProyectoDistribuidos.MessageJob.clientInfo)
        clientInfoOrBuilder {
      // Use clientInfo.newBuilder() to construct.
      private clientInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private clientInfo() {
        iP_ = "";
        port_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private clientInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                iP_ = bs;
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                port_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageDef.MessageImplementation.internal_static_ProyectoDistribuidos_MessageJob_clientInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageDef.MessageImplementation.internal_static_ProyectoDistribuidos_MessageJob_clientInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageDef.MessageImplementation.MessageJob.clientInfo.class, MessageDef.MessageImplementation.MessageJob.clientInfo.Builder.class);
      }

      private int bitField0_;
      public static final int IP_FIELD_NUMBER = 1;
      private volatile java.lang.Object iP_;
      /**
       * <code>required string IP = 1;</code>
       */
      public boolean hasIP() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string IP = 1;</code>
       */
      public java.lang.String getIP() {
        java.lang.Object ref = iP_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            iP_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string IP = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIPBytes() {
        java.lang.Object ref = iP_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PORT_FIELD_NUMBER = 2;
      private int port_;
      /**
       * <code>required int32 Port = 2;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 Port = 2;</code>
       */
      public int getPort() {
        return port_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasIP()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPort()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, iP_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, port_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, iP_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, port_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof MessageDef.MessageImplementation.MessageJob.clientInfo)) {
          return super.equals(obj);
        }
        MessageDef.MessageImplementation.MessageJob.clientInfo other = (MessageDef.MessageImplementation.MessageJob.clientInfo) obj;

        boolean result = true;
        result = result && (hasIP() == other.hasIP());
        if (hasIP()) {
          result = result && getIP()
              .equals(other.getIP());
        }
        result = result && (hasPort() == other.hasPort());
        if (hasPort()) {
          result = result && (getPort()
              == other.getPort());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasIP()) {
          hash = (37 * hash) + IP_FIELD_NUMBER;
          hash = (53 * hash) + getIP().hashCode();
        }
        if (hasPort()) {
          hash = (37 * hash) + PORT_FIELD_NUMBER;
          hash = (53 * hash) + getPort();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static MessageDef.MessageImplementation.MessageJob.clientInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MessageDef.MessageImplementation.MessageJob.clientInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MessageDef.MessageImplementation.MessageJob.clientInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MessageDef.MessageImplementation.MessageJob.clientInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MessageDef.MessageImplementation.MessageJob.clientInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static MessageDef.MessageImplementation.MessageJob.clientInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static MessageDef.MessageImplementation.MessageJob.clientInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static MessageDef.MessageImplementation.MessageJob.clientInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static MessageDef.MessageImplementation.MessageJob.clientInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static MessageDef.MessageImplementation.MessageJob.clientInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(MessageDef.MessageImplementation.MessageJob.clientInfo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ProyectoDistribuidos.MessageJob.clientInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ProyectoDistribuidos.MessageJob.clientInfo)
          MessageDef.MessageImplementation.MessageJob.clientInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return MessageDef.MessageImplementation.internal_static_ProyectoDistribuidos_MessageJob_clientInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return MessageDef.MessageImplementation.internal_static_ProyectoDistribuidos_MessageJob_clientInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  MessageDef.MessageImplementation.MessageJob.clientInfo.class, MessageDef.MessageImplementation.MessageJob.clientInfo.Builder.class);
        }

        // Construct using MessageDef.MessageImplementation.MessageJob.clientInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          iP_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          port_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return MessageDef.MessageImplementation.internal_static_ProyectoDistribuidos_MessageJob_clientInfo_descriptor;
        }

        public MessageDef.MessageImplementation.MessageJob.clientInfo getDefaultInstanceForType() {
          return MessageDef.MessageImplementation.MessageJob.clientInfo.getDefaultInstance();
        }

        public MessageDef.MessageImplementation.MessageJob.clientInfo build() {
          MessageDef.MessageImplementation.MessageJob.clientInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public MessageDef.MessageImplementation.MessageJob.clientInfo buildPartial() {
          MessageDef.MessageImplementation.MessageJob.clientInfo result = new MessageDef.MessageImplementation.MessageJob.clientInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.iP_ = iP_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.port_ = port_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof MessageDef.MessageImplementation.MessageJob.clientInfo) {
            return mergeFrom((MessageDef.MessageImplementation.MessageJob.clientInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(MessageDef.MessageImplementation.MessageJob.clientInfo other) {
          if (other == MessageDef.MessageImplementation.MessageJob.clientInfo.getDefaultInstance()) return this;
          if (other.hasIP()) {
            bitField0_ |= 0x00000001;
            iP_ = other.iP_;
            onChanged();
          }
          if (other.hasPort()) {
            setPort(other.getPort());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasIP()) {
            return false;
          }
          if (!hasPort()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          MessageDef.MessageImplementation.MessageJob.clientInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (MessageDef.MessageImplementation.MessageJob.clientInfo) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object iP_ = "";
        /**
         * <code>required string IP = 1;</code>
         */
        public boolean hasIP() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string IP = 1;</code>
         */
        public java.lang.String getIP() {
          java.lang.Object ref = iP_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              iP_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string IP = 1;</code>
         */
        public com.google.protobuf.ByteString
            getIPBytes() {
          java.lang.Object ref = iP_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            iP_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string IP = 1;</code>
         */
        public Builder setIP(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          iP_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string IP = 1;</code>
         */
        public Builder clearIP() {
          bitField0_ = (bitField0_ & ~0x00000001);
          iP_ = getDefaultInstance().getIP();
          onChanged();
          return this;
        }
        /**
         * <code>required string IP = 1;</code>
         */
        public Builder setIPBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          iP_ = value;
          onChanged();
          return this;
        }

        private int port_ ;
        /**
         * <code>required int32 Port = 2;</code>
         */
        public boolean hasPort() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 Port = 2;</code>
         */
        public int getPort() {
          return port_;
        }
        /**
         * <code>required int32 Port = 2;</code>
         */
        public Builder setPort(int value) {
          bitField0_ |= 0x00000002;
          port_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 Port = 2;</code>
         */
        public Builder clearPort() {
          bitField0_ = (bitField0_ & ~0x00000002);
          port_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:ProyectoDistribuidos.MessageJob.clientInfo)
      }

      // @@protoc_insertion_point(class_scope:ProyectoDistribuidos.MessageJob.clientInfo)
      private static final MessageDef.MessageImplementation.MessageJob.clientInfo DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new MessageDef.MessageImplementation.MessageJob.clientInfo();
      }

      public static MessageDef.MessageImplementation.MessageJob.clientInfo getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<clientInfo>
          PARSER = new com.google.protobuf.AbstractParser<clientInfo>() {
        public clientInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new clientInfo(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<clientInfo> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<clientInfo> getParserForType() {
        return PARSER;
      }

      public MessageDef.MessageImplementation.MessageJob.clientInfo getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ORIGIN_FIELD_NUMBER = 1;
    private volatile java.lang.Object origin_;
    /**
     * <code>required string origin = 1;</code>
     */
    public boolean hasOrigin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string origin = 1;</code>
     */
    public java.lang.String getOrigin() {
      java.lang.Object ref = origin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          origin_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string origin = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOriginBytes() {
      java.lang.Object ref = origin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        origin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTINY_FIELD_NUMBER = 2;
    private volatile java.lang.Object destiny_;
    /**
     * <code>required string destiny = 2;</code>
     */
    public boolean hasDestiny() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string destiny = 2;</code>
     */
    public java.lang.String getDestiny() {
      java.lang.Object ref = destiny_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destiny_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string destiny = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDestinyBytes() {
      java.lang.Object ref = destiny_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destiny_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIOR_FIELD_NUMBER = 3;
    private int prior_;
    /**
     * <code>required .ProyectoDistribuidos.MessageJob.Priority prior = 3;</code>
     */
    public boolean hasPrior() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .ProyectoDistribuidos.MessageJob.Priority prior = 3;</code>
     */
    public MessageDef.MessageImplementation.MessageJob.Priority getPrior() {
      MessageDef.MessageImplementation.MessageJob.Priority result = MessageDef.MessageImplementation.MessageJob.Priority.valueOf(prior_);
      return result == null ? MessageDef.MessageImplementation.MessageJob.Priority.HIGH : result;
    }

    public static final int INFO_FIELD_NUMBER = 4;
    private MessageDef.MessageImplementation.MessageJob.clientInfo info_;
    /**
     * <code>required .ProyectoDistribuidos.MessageJob.clientInfo info = 4;</code>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .ProyectoDistribuidos.MessageJob.clientInfo info = 4;</code>
     */
    public MessageDef.MessageImplementation.MessageJob.clientInfo getInfo() {
      return info_ == null ? MessageDef.MessageImplementation.MessageJob.clientInfo.getDefaultInstance() : info_;
    }
    /**
     * <code>required .ProyectoDistribuidos.MessageJob.clientInfo info = 4;</code>
     */
    public MessageDef.MessageImplementation.MessageJob.clientInfoOrBuilder getInfoOrBuilder() {
      return info_ == null ? MessageDef.MessageImplementation.MessageJob.clientInfo.getDefaultInstance() : info_;
    }

    public static final int OP_FIELD_NUMBER = 5;
    private int op_;
    /**
     * <code>required .ProyectoDistribuidos.MessageJob.Operation op = 5;</code>
     */
    public boolean hasOp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .ProyectoDistribuidos.MessageJob.Operation op = 5;</code>
     */
    public MessageDef.MessageImplementation.MessageJob.Operation getOp() {
      MessageDef.MessageImplementation.MessageJob.Operation result = MessageDef.MessageImplementation.MessageJob.Operation.valueOf(op_);
      return result == null ? MessageDef.MessageImplementation.MessageJob.Operation.CREATE : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOrigin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDestiny()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrior()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, origin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, destiny_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, prior_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, getInfo());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, op_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, origin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, destiny_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, prior_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getInfo());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, op_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageDef.MessageImplementation.MessageJob)) {
        return super.equals(obj);
      }
      MessageDef.MessageImplementation.MessageJob other = (MessageDef.MessageImplementation.MessageJob) obj;

      boolean result = true;
      result = result && (hasOrigin() == other.hasOrigin());
      if (hasOrigin()) {
        result = result && getOrigin()
            .equals(other.getOrigin());
      }
      result = result && (hasDestiny() == other.hasDestiny());
      if (hasDestiny()) {
        result = result && getDestiny()
            .equals(other.getDestiny());
      }
      result = result && (hasPrior() == other.hasPrior());
      if (hasPrior()) {
        result = result && prior_ == other.prior_;
      }
      result = result && (hasInfo() == other.hasInfo());
      if (hasInfo()) {
        result = result && getInfo()
            .equals(other.getInfo());
      }
      result = result && (hasOp() == other.hasOp());
      if (hasOp()) {
        result = result && op_ == other.op_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOrigin()) {
        hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
        hash = (53 * hash) + getOrigin().hashCode();
      }
      if (hasDestiny()) {
        hash = (37 * hash) + DESTINY_FIELD_NUMBER;
        hash = (53 * hash) + getDestiny().hashCode();
      }
      if (hasPrior()) {
        hash = (37 * hash) + PRIOR_FIELD_NUMBER;
        hash = (53 * hash) + prior_;
      }
      if (hasInfo()) {
        hash = (37 * hash) + INFO_FIELD_NUMBER;
        hash = (53 * hash) + getInfo().hashCode();
      }
      if (hasOp()) {
        hash = (37 * hash) + OP_FIELD_NUMBER;
        hash = (53 * hash) + op_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageDef.MessageImplementation.MessageJob parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageDef.MessageImplementation.MessageJob parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageDef.MessageImplementation.MessageJob parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageDef.MessageImplementation.MessageJob parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageDef.MessageImplementation.MessageJob parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageDef.MessageImplementation.MessageJob parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageDef.MessageImplementation.MessageJob parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessageDef.MessageImplementation.MessageJob parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageDef.MessageImplementation.MessageJob parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageDef.MessageImplementation.MessageJob parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageDef.MessageImplementation.MessageJob prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProyectoDistribuidos.MessageJob}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProyectoDistribuidos.MessageJob)
        MessageDef.MessageImplementation.MessageJobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageDef.MessageImplementation.internal_static_ProyectoDistribuidos_MessageJob_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageDef.MessageImplementation.internal_static_ProyectoDistribuidos_MessageJob_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageDef.MessageImplementation.MessageJob.class, MessageDef.MessageImplementation.MessageJob.Builder.class);
      }

      // Construct using MessageDef.MessageImplementation.MessageJob.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        origin_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        destiny_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        prior_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (infoBuilder_ == null) {
          info_ = null;
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        op_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageDef.MessageImplementation.internal_static_ProyectoDistribuidos_MessageJob_descriptor;
      }

      public MessageDef.MessageImplementation.MessageJob getDefaultInstanceForType() {
        return MessageDef.MessageImplementation.MessageJob.getDefaultInstance();
      }

      public MessageDef.MessageImplementation.MessageJob build() {
        MessageDef.MessageImplementation.MessageJob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MessageDef.MessageImplementation.MessageJob buildPartial() {
        MessageDef.MessageImplementation.MessageJob result = new MessageDef.MessageImplementation.MessageJob(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.origin_ = origin_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.destiny_ = destiny_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.prior_ = prior_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.op_ = op_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageDef.MessageImplementation.MessageJob) {
          return mergeFrom((MessageDef.MessageImplementation.MessageJob)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageDef.MessageImplementation.MessageJob other) {
        if (other == MessageDef.MessageImplementation.MessageJob.getDefaultInstance()) return this;
        if (other.hasOrigin()) {
          bitField0_ |= 0x00000001;
          origin_ = other.origin_;
          onChanged();
        }
        if (other.hasDestiny()) {
          bitField0_ |= 0x00000002;
          destiny_ = other.destiny_;
          onChanged();
        }
        if (other.hasPrior()) {
          setPrior(other.getPrior());
        }
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        if (other.hasOp()) {
          setOp(other.getOp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOrigin()) {
          return false;
        }
        if (!hasDestiny()) {
          return false;
        }
        if (!hasPrior()) {
          return false;
        }
        if (!hasInfo()) {
          return false;
        }
        if (!hasOp()) {
          return false;
        }
        if (!getInfo().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessageDef.MessageImplementation.MessageJob parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessageDef.MessageImplementation.MessageJob) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object origin_ = "";
      /**
       * <code>required string origin = 1;</code>
       */
      public boolean hasOrigin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string origin = 1;</code>
       */
      public java.lang.String getOrigin() {
        java.lang.Object ref = origin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            origin_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string origin = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOriginBytes() {
        java.lang.Object ref = origin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          origin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string origin = 1;</code>
       */
      public Builder setOrigin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        origin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string origin = 1;</code>
       */
      public Builder clearOrigin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        origin_ = getDefaultInstance().getOrigin();
        onChanged();
        return this;
      }
      /**
       * <code>required string origin = 1;</code>
       */
      public Builder setOriginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        origin_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object destiny_ = "";
      /**
       * <code>required string destiny = 2;</code>
       */
      public boolean hasDestiny() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string destiny = 2;</code>
       */
      public java.lang.String getDestiny() {
        java.lang.Object ref = destiny_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            destiny_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string destiny = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDestinyBytes() {
        java.lang.Object ref = destiny_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destiny_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string destiny = 2;</code>
       */
      public Builder setDestiny(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        destiny_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string destiny = 2;</code>
       */
      public Builder clearDestiny() {
        bitField0_ = (bitField0_ & ~0x00000002);
        destiny_ = getDefaultInstance().getDestiny();
        onChanged();
        return this;
      }
      /**
       * <code>required string destiny = 2;</code>
       */
      public Builder setDestinyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        destiny_ = value;
        onChanged();
        return this;
      }

      private int prior_ = 0;
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.Priority prior = 3;</code>
       */
      public boolean hasPrior() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.Priority prior = 3;</code>
       */
      public MessageDef.MessageImplementation.MessageJob.Priority getPrior() {
        MessageDef.MessageImplementation.MessageJob.Priority result = MessageDef.MessageImplementation.MessageJob.Priority.valueOf(prior_);
        return result == null ? MessageDef.MessageImplementation.MessageJob.Priority.HIGH : result;
      }
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.Priority prior = 3;</code>
       */
      public Builder setPrior(MessageDef.MessageImplementation.MessageJob.Priority value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        prior_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.Priority prior = 3;</code>
       */
      public Builder clearPrior() {
        bitField0_ = (bitField0_ & ~0x00000004);
        prior_ = 0;
        onChanged();
        return this;
      }

      private MessageDef.MessageImplementation.MessageJob.clientInfo info_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          MessageDef.MessageImplementation.MessageJob.clientInfo, MessageDef.MessageImplementation.MessageJob.clientInfo.Builder, MessageDef.MessageImplementation.MessageJob.clientInfoOrBuilder> infoBuilder_;
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.clientInfo info = 4;</code>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.clientInfo info = 4;</code>
       */
      public MessageDef.MessageImplementation.MessageJob.clientInfo getInfo() {
        if (infoBuilder_ == null) {
          return info_ == null ? MessageDef.MessageImplementation.MessageJob.clientInfo.getDefaultInstance() : info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.clientInfo info = 4;</code>
       */
      public Builder setInfo(MessageDef.MessageImplementation.MessageJob.clientInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.clientInfo info = 4;</code>
       */
      public Builder setInfo(
          MessageDef.MessageImplementation.MessageJob.clientInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.clientInfo info = 4;</code>
       */
      public Builder mergeInfo(MessageDef.MessageImplementation.MessageJob.clientInfo value) {
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              info_ != null &&
              info_ != MessageDef.MessageImplementation.MessageJob.clientInfo.getDefaultInstance()) {
            info_ =
              MessageDef.MessageImplementation.MessageJob.clientInfo.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.clientInfo info = 4;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = null;
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.clientInfo info = 4;</code>
       */
      public MessageDef.MessageImplementation.MessageJob.clientInfo.Builder getInfoBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.clientInfo info = 4;</code>
       */
      public MessageDef.MessageImplementation.MessageJob.clientInfoOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_ == null ?
              MessageDef.MessageImplementation.MessageJob.clientInfo.getDefaultInstance() : info_;
        }
      }
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.clientInfo info = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MessageDef.MessageImplementation.MessageJob.clientInfo, MessageDef.MessageImplementation.MessageJob.clientInfo.Builder, MessageDef.MessageImplementation.MessageJob.clientInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MessageDef.MessageImplementation.MessageJob.clientInfo, MessageDef.MessageImplementation.MessageJob.clientInfo.Builder, MessageDef.MessageImplementation.MessageJob.clientInfoOrBuilder>(
                  getInfo(),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      private int op_ = 0;
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.Operation op = 5;</code>
       */
      public boolean hasOp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.Operation op = 5;</code>
       */
      public MessageDef.MessageImplementation.MessageJob.Operation getOp() {
        MessageDef.MessageImplementation.MessageJob.Operation result = MessageDef.MessageImplementation.MessageJob.Operation.valueOf(op_);
        return result == null ? MessageDef.MessageImplementation.MessageJob.Operation.CREATE : result;
      }
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.Operation op = 5;</code>
       */
      public Builder setOp(MessageDef.MessageImplementation.MessageJob.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        op_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .ProyectoDistribuidos.MessageJob.Operation op = 5;</code>
       */
      public Builder clearOp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        op_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProyectoDistribuidos.MessageJob)
    }

    // @@protoc_insertion_point(class_scope:ProyectoDistribuidos.MessageJob)
    private static final MessageDef.MessageImplementation.MessageJob DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageDef.MessageImplementation.MessageJob();
    }

    public static MessageDef.MessageImplementation.MessageJob getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MessageJob>
        PARSER = new com.google.protobuf.AbstractParser<MessageJob>() {
      public MessageJob parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MessageJob(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageJob> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageJob> getParserForType() {
      return PARSER;
    }

    public MessageDef.MessageImplementation.MessageJob getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProyectoDistribuidos_MessageJob_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProyectoDistribuidos_MessageJob_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProyectoDistribuidos_MessageJob_clientInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProyectoDistribuidos_MessageJob_clientInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020MessageJob.proto\022\024ProyectoDistribuidos" +
      "\"\320\002\n\nMessageJob\022\016\n\006origin\030\001 \002(\t\022\017\n\007desti" +
      "ny\030\002 \002(\t\0228\n\005prior\030\003 \002(\0162).ProyectoDistri" +
      "buidos.MessageJob.Priority\0229\n\004info\030\004 \002(\013" +
      "2+.ProyectoDistribuidos.MessageJob.clien" +
      "tInfo\0226\n\002op\030\005 \002(\0162*.ProyectoDistribuidos" +
      ".MessageJob.Operation\032&\n\nclientInfo\022\n\n\002I" +
      "P\030\001 \002(\t\022\014\n\004Port\030\002 \002(\005\"-\n\tOperation\022\n\n\006CR" +
      "EATE\020\000\022\n\n\006CANCEL\020\001\022\010\n\004READ\020\002\"\035\n\010Priority" +
      "\022\010\n\004HIGH\020\000\022\007\n\003LOW\020\001B#\n\nMessageDefB\025Messa",
      "geImplementation"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProyectoDistribuidos_MessageJob_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProyectoDistribuidos_MessageJob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProyectoDistribuidos_MessageJob_descriptor,
        new java.lang.String[] { "Origin", "Destiny", "Prior", "Info", "Op", });
    internal_static_ProyectoDistribuidos_MessageJob_clientInfo_descriptor =
      internal_static_ProyectoDistribuidos_MessageJob_descriptor.getNestedTypes().get(0);
    internal_static_ProyectoDistribuidos_MessageJob_clientInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProyectoDistribuidos_MessageJob_clientInfo_descriptor,
        new java.lang.String[] { "IP", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
